### ISSUE TITLE
使えそうなリソース

### ISSUE THREAD

**Issue by natmark** [miraikeitai2017/Go-APIServer-Study#1]
Go言語の初心者が見ると幸せになれる場所　#golang
http://qiita.com/tenntenn/items/0e33a4959250d1a55045

**Comment by natmark** [comment]
Go Web プログラミング
https://astaxie.gitbooks.io/build-web-application-with-golang/content/ja/01.1.html

**Comment by m4kvn** [comment]
[miraikeitai2017/learning-resources/blob/master/Server/Go.md](https://github.com/miraikeitai2017/learning-resources/blob/master/Server/Go.md) にまとめた
